/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;

/**
 *
 * @author e-zof
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnProductos = new javax.swing.JButton();
        btnServicios = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuAbrir = new javax.swing.JMenu();
        mnuIProductos = new javax.swing.JMenuItem();
        mnuIServicios = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuISalir = new javax.swing.JMenuItem();
        mnuVersion = new javax.swing.JMenu();
        mnuVAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Menu");

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setForeground(new java.awt.Color(0, 204, 204));

        btnProductos.setText("Catalogo productos");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });

        btnServicios.setText("Lista Servicios");
        btnServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServiciosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProductos)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnServicios)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnProductos)
                .addGap(18, 18, 18)
                .addComponent(btnServicios)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        mnuAbrir.setText("Abrir");

        mnuIProductos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuIProductos.setText("Catalogo Productos");
        mnuIProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIProductosActionPerformed(evt);
            }
        });
        mnuAbrir.add(mnuIProductos);

        mnuIServicios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuIServicios.setText("Lista Servicios");
        mnuIServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIServiciosActionPerformed(evt);
            }
        });
        mnuAbrir.add(mnuIServicios);
        mnuAbrir.add(jSeparator1);

        mnuISalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuISalir.setText("Salir");
        mnuISalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuISalirActionPerformed(evt);
            }
        });
        mnuAbrir.add(mnuISalir);

        jMenuBar1.add(mnuAbrir);

        mnuVersion.setText("Version");

        mnuVAcerca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuVAcerca.setText("acerca de ");
        mnuVAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVAcercaActionPerformed(evt);
            }
        });
        mnuVersion.add(mnuVAcerca);

        jMenuBar1.add(mnuVersion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed


        
        productos ventanaProductos = new productos(); //lamada 
        
        ventanaProductos.setVisible(true); //visible
        
        this.hide();  //oculta ventana anterior;
        
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiciosActionPerformed





        // TODO add your handling code here:
        
        
            servicios ventanaServicios = new servicios(); //llamada 
            
            ventanaServicios.setVisible(true); //visible
            
            this.hide(); //oculta ventana
        
        
    }//GEN-LAST:event_btnServiciosActionPerformed

    private void mnuIProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIProductosActionPerformed
        // TODO add your handling code here:

        
        productos ventanaProductos = new productos(); //lamada 
        
        ventanaProductos.setVisible(true); //visible
        
        this.hide();  //oculta ventana anterior;
    }//GEN-LAST:event_mnuIProductosActionPerformed

    private void mnuIServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIServiciosActionPerformed


        // TODO add your handling code here:
        
        
            servicios ventanaServicios = new servicios(); //llamada 
            
            ventanaServicios.setVisible(true); //visible
            
            this.hide(); //oculta ventana
        

        // TODO add your handling code here:
    }//GEN-LAST:event_mnuIServiciosActionPerformed

    private void mnuISalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuISalirActionPerformed
        // TODO add your handling code here:

        System.exit(0); // cierra ventana
    }//GEN-LAST:event_mnuISalirActionPerformed

    private void mnuVAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVAcercaActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(null, "Software 1.0 \n \n Administración y gestion \n\n  Powered by Zoflabs ");
        
        
    }//GEN-LAST:event_mnuVAcercaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnServicios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu mnuAbrir;
    private javax.swing.JMenuItem mnuIProductos;
    private javax.swing.JMenuItem mnuISalir;
    private javax.swing.JMenuItem mnuIServicios;
    private javax.swing.JMenuItem mnuVAcerca;
    private javax.swing.JMenu mnuVersion;
    // End of variables declaration//GEN-END:variables
}
