/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OperacionesFor;

import javax.swing.JOptionPane;

/**
 *
 * @author e-zof
 */
public class MenuArreglos extends javax.swing.JFrame {

    /**
     * Creates new form MenuArreglos
     */
    public MenuArreglos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEjercicios = new javax.swing.JLabel();
        btnArregloFloat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblEjercicios.setText("Ejercicios Arreglos, operaciones Zuñiga");

        btnArregloFloat.setText("Arreglo Calificacion (float)");
        btnArregloFloat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArregloFloatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(lblEjercicios))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(btnArregloFloat)))
                .addContainerGap(253, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblEjercicios)
                .addGap(75, 75, 75)
                .addComponent(btnArregloFloat)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnArregloFloatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArregloFloatActionPerformed

        //entrada declaracion de arreglo
        float arregloCalifica[] = new float[300];

        //para capturar N calificaciones 
        String ventanaNElementos = JOptionPane.showInputDialog("Bienvenido a CC de control escolar \n \n Captura el número de Elementos en Lista: ");
        int nElementos = Integer.parseInt(ventanaNElementos);

        //para capturar los valores en el arreglo
        for (int i = 0; i < nElementos; i++) {
            String ventanaCaptura = JOptionPane.showInputDialog("Captura calificación [ " + (i + 1) + "]");

            //arreglo para almacenar valores 
            arregloCalifica[i] = Float.parseFloat(ventanaCaptura);

        }

        //PROCESO calculos, operaciones 
        //para sumar y promediar calificaciones del arreglo
        float sumaCalificaciones = 0.0f;

        for (int i = 0; i < nElementos; i++) {

            sumaCalificaciones = sumaCalificaciones + arregloCalifica[i]; //sumador

        }

        //SALIDA
        //para imprimir valores del arreglo
        String acumulador = "";

        for (int i = 0; i < nElementos; i++) {

            //acumulador = agregando, integreando componentes 
            acumulador += "\n Tu calificación es " + (i + 1) + " :" + arregloCalifica[i];

        }//termina for

        //  JOptionPane.showMessageDialog(null, "tu calificación es :" + arregloCalifica[i]); //para imprimir de uno en uno 
        JOptionPane.showMessageDialog(null, "Lista de alumnos \n\n" + acumulador
                + "\n-----------------------------"
                + "\n\nSuma  de calificaciones " + sumaCalificaciones
                + "\n-----------------------------"
                + "\n\n Promedio calificaciones : " + (sumaCalificaciones / nElementos)
                + "\n-----------------------------"
                + "\n\nAutor: xXZOFXx");


    }//GEN-LAST:event_btnArregloFloatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuArreglos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuArreglos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuArreglos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuArreglos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuArreglos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArregloFloat;
    private javax.swing.JLabel lblEjercicios;
    // End of variables declaration//GEN-END:variables
}
