/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author e-zof
 */
public class Parseo extends javax.swing.JFrame {

    /**
     * Creates new form Parseo
     */
    public Parseo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblParseo = new javax.swing.JLabel();
        lblWEntero = new javax.swing.JLabel();
        txtEntrada = new javax.swing.JTextField();
        lblSalida = new javax.swing.JLabel();
        txtSalida = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblParseo.setForeground(new java.awt.Color(255, 255, 255));
        lblParseo.setText("Parseo (conversión de objeto a primitiva)");
        getContentPane().add(lblParseo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, 30));

        lblWEntero.setForeground(new java.awt.Color(255, 255, 255));
        lblWEntero.setText("Decimal");
        getContentPane().add(lblWEntero, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 108, -1, -1));

        txtEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntradaActionPerformed(evt);
            }
        });
        getContentPane().add(txtEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 104, 105, -1));

        lblSalida.setForeground(new java.awt.Color(255, 255, 255));
        lblSalida.setText("Salida");
        getContentPane().add(lblSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 157, -1, -1));
        getContentPane().add(txtSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 153, 105, -1));

        btnAceptar.setBackground(new java.awt.Color(0, 102, 102));
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/e-zof/Descargas/profile.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 610, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // entrada declaracion de bariables enteras
        
        //byte variableEntera = Byte.parseByte(this.txtEntrada.getText());//entero corto
        
        // int variableEntera = Integer.parseInt(this.txtEntrada.getText());//entero Regular
        
       // long variableEntera = Long.parseLong(this.txtEntrada.getText());//entero Largo 

       
       //declaracionde variables decimales
       
       //float varDecimalCorto = Float.parseFloat(this.txtEntrada.getText());
       
       
       //char varCaracter = 'A'; //variable inicializada char es un caracter
      
       
       String entradaCaracter = this.txtEntrada.getText(); //cadena de caracteres (sin parseo, porque no lo necesita) 
       
        //char varCaracter = entradaCaracter.charAt(0); //variable indefinida 
       
        //proceso 
        
        
        //salida imprimir 
        
        this.txtSalida.setText("" +  entradaCaracter);
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntradaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parseo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parseo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parseo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parseo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Parseo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblParseo;
    private javax.swing.JLabel lblSalida;
    private javax.swing.JLabel lblWEntero;
    private javax.swing.JTextField txtEntrada;
    private javax.swing.JTextField txtSalida;
    // End of variables declaration//GEN-END:variables
}
